### ISSUE TITLE
Use Makefile instead of a bash script

### ISSUE THREAD

**Issue by GPlaczek** [Linux-Academic-Group/rocket-lag-debian#1]
Plain bash script is cringe, let's use Makefile instead :)

**Comment by randoragon** [comment]
Just to be clear, there's been no progress on this issue since my last commit on Aug 24th - honestly I feel like the shell script approach works well enough for our use case and forcibly rewriting it into a Makefile wouldn't bring many benefits, but I've been slightly out of touch with this project, so let me know if my reasoning is up-to-date. If so, I'd like to close this.

**Comment by GPlaczek** [comment]
You're right, this issue is no longer relevant, feel free to close it
